const fs = require('fs')
const content = fs.readFileSync('src/app/actions/matchActions.ts', 'utf8')
const lines = content.split('\n')
const idx = lines.findIndex(l => l.includes('export async function advanceTournament'))
console.log(lines.slice(idx, idx+20).join('\n'))
